builders:
  loading_method_builder:
    import: "package:flapjack/builders.dart"
    builder_factories: ["loadingMethodBuilder"]
    build_extensions: { ".dart": [".flapjack.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]