builders:
  async_loader_builder:
    import: "package:flapjack/src/generators/builders.dart"
    builder_factories: ["asyncLoaderBuilder"]
    build_extensions: { ".dart": [".flapjack.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]